### ISSUE TITLE
Ch 3: Spec code written as normal text

### ISSUE THREAD

**Issue by coalwater** [everydayrails/rails-4-1-rspec-3-0#35] opened 2014-12-06 22:56 UTC
I found an example spec which is written in normal text, the code doesn't even contain line breaks so it's very hard to read
I found the issue existing in the PDF and mobi versions, so I assume it also exists in the epub version.
It's under the `Testing Validations` in chapter 3, highlighted in gray in the screenshot  

![screenshot](https://cloud.githubusercontent.com/assets/1215841/5329222/98f4a144-7dab-11e4-9932-8012aa0a8a6c.png)

**Comment by ruralocity** [comment] 2014-12-14 01:13
Thanks—this is a duplicate of #29, which I've addressed for the forthcoming maintenance release.

**Closed as completed by ruralocity** 2014-12-14 01:13 UTC

**Comment by coalwater** [comment] 2014-12-14 10:37
O ok, sorry didn't check old issues
